version: "3"
services:
  latest:
    container_name: m1bar_latest
    image: digiccy
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./run.sh:/app/run.sh
      - ./conf.json:/app/conf/json
    command: bash run.sh
